import { Space_Mono } from "next/font/google";
import "./globals.css";

const space_mono = Space_Mono({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "devfinder - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${space_mono.className} flex min-h-screen w-screen flex-col items-center justify-center bg-[#141C2F] text-zinc-50`}
      >
        <main className="w-full max-w-screen-md p-6">{children}</main>
      </body>
    </html>
  );
}
